DROP DATABASE SENAattendance;
CREATE DATABASE SENAattendance;
USE SENAattendance;

CREATE TABLE Carrera(
    Id_Car INT PRIMARY KEY AUTO_INCREMENT,
    Nom_Car VARCHAR(150) NOT NULL,
    Des_Car TEXT NULL,
    Fec_Cre DATETIME DEFAULT CURRENT_TIMESTAMP,
    Fec_Mod DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Fichas (
    Id_Fic INT PRIMARY KEY AUTO_INCREMENT,
    Id_Car INT NOT NULL,
    Fec_inicio_Fic DATE NOT NULL,
    Fec_Fin_Fic DATE NOT NULL,
    Num_Fic INT NOT NULL UNIQUE,
    Jor_Fic ENUM("Mañana","Tarde","Noche") NOT NULL,
    Fec_Cre DATETIME DEFAULT CURRENT_TIMESTAMP,
    Fec_Mod DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(Id_Car) REFERENCES Carrera(Id_Car)
);

CREATE TABLE competencia(
    Id_Comp INT PRIMARY KEY AUTO_INCREMENT,
    Nom_Comp VARCHAR(150) NOT NULL,
    Des_Comp TEXT NULL,
    Fec_Cre DATETIME DEFAULT CURRENT_TIMESTAMP,
    Fec_Mod DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Instructor (
    Id_Ins INT PRIMARY KEY AUTO_INCREMENT,
    Nom_Ins VARCHAR(100) NOT NULL,
    Ape_Ins VARCHAR(100) NOT NULL,
    Tip_ide_Ins ENUM("CC","TI","CE","PEP","PPT") NOT NULL,
    Num_ide_Ins INT NOT NULL UNIQUE,
    Cor_Ins VARCHAR(100) NOT NULL UNIQUE,
    Con_Ins VARCHAR(255) NOT NULL,
    Es_Ins BOOLEAN NOT NULL DEFAULT TRUE,
    Fec_Cre DATETIME DEFAULT CURRENT_TIMESTAMP,
    Fec_Mod DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Administrador (
    Id_Adm INT PRIMARY KEY AUTO_INCREMENT,
    Nom_Adm VARCHAR(100) NOT NULL,
    Ape_Adm VARCHAR(100) NOT NULL,
    Tip_ide_Adm ENUM("CC","TI","CE","PEP","PPT") NOT NULL,
    Num_ide_Adm INT NOT NULL UNIQUE,
    Cor_Adm VARCHAR(100) NOT NULL UNIQUE,
    Con_Adm VARCHAR(255) NOT NULL,
    Es_Adm BOOLEAN NOT NULL DEFAULT TRUE,
    Fec_Cre DATETIME DEFAULT CURRENT_TIMESTAMP,
    Fec_Mod DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
		
CREATE TABLE Aprendiz (
    Id_Apr INT PRIMARY KEY AUTO_INCREMENT,
    Nom_Apr VARCHAR(100) NOT NULL,
    Ape_Apr VARCHAR(100) NOT NULL,
    Tip_ide_Apr ENUM("CC","TI","CE","PEP","PPT") NOT NULL,
    Num_ide_Apr INT NOT NULL UNIQUE,
    Cor_Apr VARCHAR(100) NOT NULL UNIQUE,
    Con_Apr VARCHAR(255) NOT NULL,
    Es_Apr BOOLEAN NOT NULL DEFAULT TRUE,
    Id_Fic INT NOT NULL,
    Fec_Cre DATETIME DEFAULT CURRENT_TIMESTAMP,
    Fec_Mod DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Id_Fic) REFERENCES Fichas(Id_Fic)
);

CREATE TABLE Ficha_Instructor (
    Id_Fic INT NOT NULL,
    Id_Ins INT NOT NULL,
    PRIMARY KEY (Id_Fic, Id_Ins),
    FOREIGN KEY (Id_Fic) REFERENCES Fichas(Id_Fic),
    FOREIGN KEY (Id_Ins) REFERENCES Instructor(Id_Ins)
);

CREATE TABLE ResultadoAprendizaje (
    Id_RA INT PRIMARY KEY AUTO_INCREMENT,
    Nom_RA VARCHAR(150) NOT NULL,
    Des_RA TEXT NULL,
    Id_Fic INT NOT NULL,
    Id_Comp INT NOT NULL,
    Fec_Cre DATETIME DEFAULT CURRENT_TIMESTAMP,
    Fec_Mod DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Id_Fic) REFERENCES Fichas(Id_Fic),
    FOREIGN KEY (Id_Comp) REFERENCES competencia(Id_Comp)
);

CREATE TABLE Asistencia (
    Id_Asi INT PRIMARY KEY AUTO_INCREMENT,
    Fec_Asi DATE NOT NULL,
    Es_Asi ENUM("Retardo","Excusa","Falla","Presente") NOT NULL,
    Id_Apr INT NOT NULL,
    Id_Fic INT NOT NULL,
    Fec_Cre DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Id_Apr) REFERENCES Aprendiz(Id_Apr),
    FOREIGN KEY (Id_Fic) REFERENCES Fichas(Id_Fic)
);

CREATE TABLE Notificacion (
    Id_Not INT PRIMARY KEY AUTO_INCREMENT,
    Asu_Not TEXT NOT NULL,
    Men_Not TEXT NOT NULL,
    Fec_Not DATE NOT NULL,
    Id_Apr INT NULL,
    Id_Ins INT NULL,
    Id_Adm INT NULL,
    Fec_Cre DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Id_Apr) REFERENCES Aprendiz(Id_Apr),
    FOREIGN KEY (Id_Ins) REFERENCES Instructor(Id_Ins),
    FOREIGN KEY (Id_Adm) REFERENCES Administrador(Id_Adm)
);

CREATE TABLE Log (
    Id_Log INT PRIMARY KEY AUTO_INCREMENT,
    Tabla_Afectada VARCHAR(50) NOT NULL,
    Id_Registro INT NOT NULL,
    Accion ENUM("INSERT","UPDATE","DELETE") NOT NULL,
    Usu_Log VARCHAR(100) NOT NULL,
    Fec_Log DATETIME DEFAULT CURRENT_TIMESTAMP,
    Det_Log TEXT NULL
);

ALTER TABLE Aprendiz MODIFY Id_Fic INT NULL;

INSERT INTO Aprendiz (Nom_Apr, Ape_Apr, Tip_ide_Apr, Num_ide_Apr, Cor_Apr, Con_Apr)
VALUES (
    'Alejandro',
    'Prueba',
    'TI',
    1234567890,
    'alejandro.prueba@sena.edu.co',
    'scrypt:32768:8:1$jmAas7Lm9lfDzTZ9$3080f58433b821b277f640fafa71585ecc2460e8323c224d311ec63e36a7d25fc1552f16aed9998017d9602173c7f4e1203e290f8445346044581ec55814b613'
);

INSERT INTO Administrador (Nom_Adm, Ape_Adm, Tip_ide_Adm, Num_ide_Adm, Cor_Adm, Con_Adm)
VALUES (
    'Samuel',
    'Bravo',
    'CC',
    1234567891,
    'samuel.bravo@sena.edu.co',
    'scrypt:32768:8:1$cOtZGeAQAHkSqeyi$172e3027678cde86d1af9168592f74c581b096096c7dd403ab17c99b496142c1f0fc81a0437b691af00add46bf96f9fbca3fe0b8c69fee48ceffed72d24630a6'
);

INSERT INTO Carrera (Nom_Car, Des_Car)
VALUES (
    'ADSO',
    'Analisis y Desarrollo de software'
);

INSERT INTO Fichas (Id_Car, Fec_inicio_Fic, Fec_Fin_Fic, Num_Fic, Jor_Fic)
VALUES (
	1,
    '2026-06-29',
    '2027-06-07',
    3407184,
    'Mañana'
);

select * from Administrador;
select * from Aprendiz;